config/routes.rb
Rails.application.routes.draw do

  resources :exercises
  delete 'remove_exercise/:id' => 'exercises#remove_exercise'
  devise_for :users, controllers: {sessions: "sessions"}


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # scope admin
  get '/admin/dashboard', to: 'admin#dashboard'
  get '/admin/index', to: 'admin#index'
  get '/admin/my_profile', to: 'admin#my_profile'

  # admin, superadmin only
  get '/admin/logopedisten', to: 'admin#logopedisten'
  get '/admin/logs', to: 'admin#logs'

  # api functions
  get '/api/sso', to: 'api#sso'
  post '/api/add_client', to: 'api#add_client_for_user'
  get '/api/client_credentials', to: 'api#get_client_credentials'

  authenticated do
    get 'site/demo', to: 'site#demo'
  end

  # users
  namespace :admin do
    resources :users
    get 'users/:id/add_exercise/:ex_id', to: 'users#add_exercise'
    get 'users/:id/remove_exercise/:ex_id', to: 'users#remove_exercise'
    get 'preview_video/', to: 'users#preview_video'
    get 'clients', to: 'clients#index'
    get 'clients/new', to: 'clients#new'
    get 'clients/:id', to: 'clients#show'
    get 'reset_password_email/:id', to: 'clients#reset_password_email'
    get 'impersonate/(:id)' => 'users#impersonate', as: :impersonate
    #get 'stop_impersonating' => 'users#stop_impersonating', as: :stop_impersonate
    post 'stop_impersonating' => 'users#stop_impersonating', as: :stop_impersonate
  end

  # for everyone
  get '/users/my_profile', to: 'users#my_profile'

  # scope?
  # get '/app/test_api', to: 'app#test_api'
  get '/app/login(/:login)', to: 'app#login'
  post '/app/new_login', to: 'app#new_login'
  get '/app/login_failed', to: 'app#login_failed'
  get '/app/forgot_password', to: 'app#forgot_password'

  get '/app/introductie(/:token)', to: 'app#introductie'
  get '/app/info(/:token)', to: 'app#info'
  get '/app/awards(/:token)', to: 'app#awards'
  get '/app/awards/claim/:id(/:token)', to: 'app#claim_reward'
  get '/app/claim_reward/:id(/:token)', to: 'app#claim_reward'
  get '/app/claim_streak/(:token)', to: 'app#claim_streak'
  get '/app/oefening/:id(/:token)', to: 'app#oefening'
  get '/app/oefeningen(/:token)', to: 'app#oefeningen'
  get '/app/my_profile(/:token)', to: 'app#my_profile'
  get '/app/update_exercise/:id/:token', to: 'exercises#update_exercise'
  get '/app(/:token)', to: 'app#index'

  # forgot pass? -- for app users
  get '/app/password/sent' => 'app#forgot_password_confirm'
  get '/app/password/new' => 'app#forgot_password'
  get '/app/password/edit(/:user_id)' => 'app#edit_password', as: :app_password_edit
  patch '/app/password' => 'app#update_password'
  put '/app/password' => 'app#update_password'
  post '/app/password' => 'app#create_password'

  # scope site
  get '/site/index', to: 'site#index'
  get '/site/test', to: 'site#test'
  get '/site/app', to: 'site#app'

  # aliasses
  get '/sign_up', to: redirect('/users/sign_up')
  get '/inschrijven', to: redirect('/users/sign_in')
  get '/inloggen', to: redirect('/users/sign_in')
  get '/login', to: redirect('/users/sign_in')

  # test
  get 'autologintest', to: 'app#autologintest'

  root to: 'application#index'
  # match '*all', controller: 'application', action: 'cors_preflight_check', via: [:options]

  # config/routes.rb
  resources :web_hits, :only=>[:create]
  match '*all', :controller => 'web_hits', :action => 'options', :constraints => {:method => 'OPTIONS'}, via: [:options]

end

app/views/admin/_header.html.haml
.logo
  = link_to "/", :class => "imagelink" do
    = image_tag "logo_medium"

.title.handwriting.lg
  = t('admin.top_menu.payoff')

.user-actions
  = link_to "my app", "/app/oefeningen/#{current_user.authorisation_token}", :target=>"_blank"
  &nbsp;|&nbsp;
  = link_to "my profile", "/admin/users/#{current_user.id.to_s}/edit"
  &nbsp;|&nbsp;
  = link_to "logout", destroy_user_session_path, :method => :delete
  &nbsp;|&nbsp;
  /%span#language
  /  %a#language_select{:href=>"javascript:"}
  /    = I18n.locale
  /    %i.fa.fas.fa-caret-down
  /  %ul#language_dropdown
  /    %li.dropdown-item
  /      %a{:href=>"?locale=nl"} nl
  /    %li.dropdown-item
  /      %a{:href=>"?locale=vls"} vls
  /    %li.dropdown-item
  /      %a{:href=>"?locale=fr"} fr
  /    %li.dropdown-item
  /      %a{:href=>"?locale=en"} en

app/views/admin/_menu.html.haml
%ul.nav
  %li
    = link_to "Dashboard", "/"
  %li
    = link_to "Clienten", "/admin/clients"
  %li
    = link_to "Oefeningen", exercises_path

  - if current_user.has_role?(:admin) || current_user.has_role?(:superadmin)
    %li
      = link_to "Logopedisten", '/admin/logopedisten'
    %li
      = link_to "Alle gebruikers", '/admin/users'
    %li
      = link_to "Logs", '/admin/logs'

app/views/admin/_oefening_item.html.haml
- preset = lookup_exercies(exercise.preset)
- if exercise.claimed_award || exercise.completed
  %li

    .btn-group{:style=>"float:right"}
      =# link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' }
      = link_to "/remove_exercise/#{exercise.id}", method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger pull-right" do
        %i.fa.fas.fa-trash
      &nbsp;
      = link_to "/exercises/#{exercise.id}/edit", :class => "btn btn pull-right" do
        %i.fa.fas.fa-edit

      &nbsp;
      = link_to "/app/oefening/#{exercise.id}", :target=>"_blank", :class => "btn btn pull-right" do
        %i.fa.fas.fa-eye

    .empty_container{:style=>"min-height:42px;"}
      %div{:style=>"float:left;width:100px;"}
        .thumbnail{:style=>""}
          %image{:src=> preset[I18n.locale.to_s]["thumbnail"], :style=>"width:64px;"}

      %div{:style=>"float:left;width:200px;"}
        %b= preset[I18n.locale.to_s]["naam"]
        = (exercise.claimed_award? ? "<small>(Prijs opgehaald)</small>".html_safe : "<small>(Afgerond)</small>".html_safe)

- else
  %li

    .btn-group{:style=>"float:right"}
      = link_to "/remove_exercise/#{exercise.id}", method: :delete, data: { confirm: t('common.are_you_sure') }, :class => "btn btn-danger pull-right" do
        %i.fa.fas.fa-trash
      &nbsp;
      = link_to "/exercises/#{exercise.id}/edit", :class => "btn btn pull-right" do
        %i.fa.fas.fa-edit

      &nbsp;
      = link_to "/app/oefening/#{exercise.id}", :target=>"_blank", :class => "btn btn pull-right" do
        %i.fa.fas.fa-eye


    .content{:style=>""}
      .thumbnail{:style=>""}
        %image{:src=> preset[I18n.locale.to_s]["thumbnail"], :style=>"width:200px;"}

      .tekst{:style=>""}
        %h3
          = preset[I18n.locale.to_s]["naam"]
          = ( exercise.completed? ? "(afgerond)" : "" )
          %br
          %small
            sinds
            = l(exercise.created_at, :format => :short)
            ,
            = time_ago_in_words(exercise.created_at)
            geleden
        - unless exercise.completed?
          .description= preset[I18n.locale.to_s]["doel"]


      .score
        - width = 100.0

        .progress-bar
          - addToday = exercise.frequency - exercise.achieved_array_today.sum
          - exercise_total = exercise.target * exercise.frequency
          - Array.new(exercise_total).each_with_index do |i, index|

            - if exercise.achieved_array[index] == 0
              .progress-tic.green{:style=>"width:#{ width / exercise_total }%;"}

            - elsif exercise.achieved_array[index] == 1
              .progress-tic.lightgreen{:style=>"width:#{ width / exercise_total }%;"}

            - elsif addToday > 0 && exercise.completed_for_the_day == false
              -# left_today = exercise.frequency - exercise.achieved_array_today.sum
              - addToday = addToday - 1
              .progress-tic.orange{:style=>"width:#{ width / exercise_total }%;"}

            - else
              .progress-tic.hollow{:style=>"width:#{ width / exercise_total }%;"}

        - unless exercise.completed
          .moving_total{:style=>"margin-left: calc( #{ exercise.achieved_array.count * ( width / exercise_total )}% - 4px );"}
            = exercise.achieved_array.sum
    /%br
    /= link_to "zet herinnering", "/view_exercise/#{exercise.id}", :class => "btn btn-danger"
    /= datetime_field_tag "reminder_date", (DateTime.now() + 36.hours).strftime("%Y-%d-%mT%H:%M")

    /%br
    /%br
    /%br
    /8 van
    /= number_field_tag "oefening_herhalingen", 12

app/views/admin/_oefening_new.html.haml
%li.new_exercise{:class=>exercise['hidden'], "data-id":exercise["id"], :id=>"new_exercise_#{exercise['id']}"}    
  .content
    %h3.title= exercise[ I18n.locale.to_s ]["naam"]
    .check_add 
      selecteer
      //= form.check_box "new_exercise_#{exercise['id']}", {:class=>"select_new_exercise", :type=>"checkbox", "data-id":exercise["id"], :id=>"exercise_#{exercise['id']}"} 
      %input.select_new_exercise{:type=>"checkbox", "data-id":exercise["id"], :id=>"new_exercise_#{exercise['id']}"}   

    // %pre= exercise[ I18n.locale.to_s ].to_yaml

    .left_col
      .thumbnail{:style=>"float:left;margin-right:12px"}
        %image{:src=>exercise[ I18n.locale.to_s ]["thumbnail"], :width=>"200px"}

    .right_col
      .category
        categorie:
        %em= exercise[ I18n.locale.to_s ]["category"]
      .tags
        tags:
        %small= exercise[ I18n.locale.to_s ]["tags"].to_sentence(last_word_connector: 'en') unless exercise[ I18n.locale.to_s ]["tags"].blank?

      .materiaal
        Materiaal:
        %em= exercise["materiaal"]
      %br
      .description{:width=>"100%"}= exercise[ I18n.locale.to_s ]["doel"].strip() unless exercise[ I18n.locale.to_s ]["doel"].blank?
      %br

      %label doel (dagen):
      %input.new_exercise_input{:type=>"number", :value=> "10", :id=>"target_#{exercise['id']}" }
      %br
      %label frequentie:
      %input.new_exercise_input{:type=>"number", :value=> exercise['frequentie'], :id=>"frequency_#{exercise['id']}" }
      %br

      %hr
      - if exercise["materiaal"] == "video"
        = link_to "Bekijk video", "/admin/preview_video/?url=" + CGI.escape(exercise[ I18n.locale.to_s ]["content"]), :class=>"btn", :target=>"_blank"
      - elsif exercise["materiaal"] == "audio"
        = link_to "Beluister audio", exercise[ I18n.locale.to_s ]["content"], :class=>"btn", :target=>"_blank"
      - elsif exercise["materiaal"] == "tekst"
        = link_to "Lees text", "javascript:void(0)", :onclick => "javascript:show_text('#{exercise[ I18n.locale.to_s ]["naam"]}', '#{exercise[ I18n.locale.to_s ]["content"]}');", :class=>"btn"
      - else
        = link_to "Bekijk #{exercise["materiaal"]}", exercise[ I18n.locale.to_s ]["content"], :class=>"btn", :target=>"_blank"

      &nbsp;
      |
      &nbsp;
      - ex_id = exercise["id"]
      = link_to " + voeg toe", "javascript:addExercise(#{ex_id})", :class=>"btn btn-turq"

    %hr

:javascript
  var addExercise = function(_id) {
    console.log("add exercise ", _id)
    var freq = document.getElementById("frequency_" + _id).value
    var target = document.getElementById("target_" + _id).value
    url = "/admin/users/#{@user.id}/add_exercise/" + _id + "?freqency=" + freq + "&target=" + target
    window.location.href = url
  }

app/views/admin/index.html.haml
%h1 Voicebuddy dashboard
.welcome
  Welkom #{current_user.email}
  /#{current_user.id} #{current_user.roles}

.clients
  %h3
    Voortgang van clienten
    %small (laatste 10)

  %table
    %thead
      %tr
        %th naam
        %th email
        %th # active oefeningen
        %th # afgeronde oef.
        %th # laatste actie

    %tbody
      - index = 0
      - User.where(:logopedist => current_user).order(:updated_at => 1).to_a.each_with_index do |client|
      - active_exercises = client.exercises.where(:claimed_award => false)
        - next if active_exercises.count == 0 || index > 10
        - index = index += 1
        %tr
          %td= client.full_name
          %td= client.email
          %td= active_exercises.count
          %td= client.exercises.where(:claimed_award => true).count
          %td= active_exercises.order(:updated_at => 1).first.updated_at unless active_exercises.count == 0
    %br

- if current_user.has_role?(:admin)
  %br
  %br
  .clients
    %h3
      Nieuwe aanmeldingen

    %table
      %thead
        %tr
          %th naam
          %th email
          %th datum
          %th
          %th

      %tbody
        - User.where(:roles.in => [:demo]).order(:updated_at => 1).each do |demo_user|
          %tr
            %td= demo_user.full_name
            %td= demo_user.email
            %td{:style=>"text-align:center"}= l(demo_user.created_at, :format => :short)
            %td= link_to t('common.edit'), edit_admin_user_path(demo_user)
            %td= link_to t('common.destroy'), "/admin/users/#{demo_user.id.to_s}", method: :delete, data: { confirm: 'Are you sure?' }
      %br

app/views/admin/logopedisten.html.haml
%p#notice= notice
%h1= t('common.speech_therapists')

.filters
  .pull-right{:style=>"float:right;"}
    %input#search_input{:value=>@search}
    %button#search search

  %p
    Page:
    %b= @page * PER_PAGE
    \/
    %b= @total


%table
  %thead
    %tr
      %th= t('common.name')
      %th= t('common.email')
      %th= t('common.roles')
      %th  clients
      %th  last sign_in
      %th{colspan: "4"}
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= user.roles.to_sentence
        %td= User.where(:logopedist => user).count
        %td= user.last_sign_in_at
        %td= link_to t('common.show'), "/admin/users/#{user.id.to_s}"
        %td= link_to t('common.impersonate'), "/admin/impersonate/#{user.id.to_s}"
        %td= link_to t('common.edit'), edit_admin_user_path(user)
        %td= link_to t('common.destroy'), "/admin/users/#{user.id.to_s}", method: :delete, data: { confirm: 'Are you sure?' }

%br  
  = render "/admin/partials/pagination", :pagination_for => "logopedisten"
  
%br

%br
%hr
%br/
= link_to t('common.new'), new_admin_user_path
=# link_to t('common.show'), new_admin_logepedist_path

app/views/admin/logs.html.haml
%h1 logs

app/views/admin/my_profile.html.haml
%h1 My Profile

= current_user.name
%br
= current_user.email
%br
= current_user.roles

= current_user.id