config/routes.rb
Rails.application.routes.draw do

  resources :exercises
  delete 'remove_exercise/:id' => 'exercises#remove_exercise'
  devise_for :users, controllers: {sessions: "sessions"}


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # scope admin
  get '/admin/dashboard', to: 'admin#dashboard'
  get '/admin/index', to: 'admin#index'
  get '/admin/my_profile', to: 'admin#my_profile'

  # admin, superadmin only
  get '/admin/logopedisten', to: 'admin#logopedisten'
  get '/admin/logs', to: 'admin#logs'

  # api functions
  get '/api/sso', to: 'api#sso'
  post '/api/add_client', to: 'api#add_client_for_user'
  get '/api/client_credentials', to: 'api#get_client_credentials'

  authenticated do
    get 'site/demo', to: 'site#demo'
  end

  # users
  namespace :admin do
    resources :users
    get 'users/:id/add_exercise/:ex_id', to: 'users#add_exercise'
    get 'users/:id/remove_exercise/:ex_id', to: 'users#remove_exercise'
    get 'preview_video/', to: 'users#preview_video'
    get 'clients', to: 'clients#index'
    get 'clients/new', to: 'clients#new'
    get 'clients/:id', to: 'clients#show'
    get 'reset_password_email/:id', to: 'clients#reset_password_email'
    get 'impersonate/(:id)' => 'users#impersonate', as: :impersonate
    #get 'stop_impersonating' => 'users#stop_impersonating', as: :stop_impersonate
    post 'stop_impersonating' => 'users#stop_impersonating', as: :stop_impersonate
  end

  # for everyone
  get '/users/my_profile', to: 'users#my_profile'

  # scope?
  # get '/app/test_api', to: 'app#test_api'
  get '/app/login(/:login)', to: 'app#login'
  post '/app/new_login', to: 'app#new_login'
  get '/app/login_failed', to: 'app#login_failed'
  get '/app/forgot_password', to: 'app#forgot_password'

  get '/app/introductie(/:token)', to: 'app#introductie'
  get '/app/info(/:token)', to: 'app#info'
  get '/app/awards(/:token)', to: 'app#awards'
  get '/app/awards/claim/:id(/:token)', to: 'app#claim_reward'
  get '/app/claim_reward/:id(/:token)', to: 'app#claim_reward'
  get '/app/claim_streak/(:token)', to: 'app#claim_streak'
  get '/app/oefening/:id(/:token)', to: 'app#oefening'
  get '/app/oefeningen(/:token)', to: 'app#oefeningen'
  get '/app/my_profile(/:token)', to: 'app#my_profile'
  get '/app/update_exercise/:id/:token', to: 'exercises#update_exercise'
  get '/app(/:token)', to: 'app#index'

  # forgot pass? -- for app users
  get '/app/password/sent' => 'app#forgot_password_confirm'
  get '/app/password/new' => 'app#forgot_password'
  get '/app/password/edit(/:user_id)' => 'app#edit_password', as: :app_password_edit
  patch '/app/password' => 'app#update_password'
  put '/app/password' => 'app#update_password'
  post '/app/password' => 'app#create_password'

  # scope site
  get '/site/index', to: 'site#index'
  get '/site/test', to: 'site#test'
  get '/site/app', to: 'site#app'

  # aliasses
  get '/sign_up', to: redirect('/users/sign_up')
  get '/inschrijven', to: redirect('/users/sign_in')
  get '/inloggen', to: redirect('/users/sign_in')
  get '/login', to: redirect('/users/sign_in')

  # test
  get 'autologintest', to: 'app#autologintest'

  root to: 'application#index'
  # match '*all', controller: 'application', action: 'cors_preflight_check', via: [:options]

  # config/routes.rb
  resources :web_hits, :only=>[:create]
  match '*all', :controller => 'web_hits', :action => 'options', :constraints => {:method => 'OPTIONS'}, via: [:options]

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  # includes roles
  include UserRolable
  field :roles, :type => Array, default: []

  # ensure api values
  before_save :check_api_token

  # a logopedist can have many clients
  # a client has one logopedists
  # both are users
  has_many :clients, :class_name => 'User', :foreign_key => :client_id, dependent: :destroy
  belongs_to :logopedist, :class_name => 'User', optional: true

  # can have exercises
  has_many :exercises

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time


  # ----------------------------------------------------------------------------
  # I'll write my own role system with booze and hookers
  field :name, type: String, default: ""
  field :client_id, type: String, default: ""

  # just for the heck of it
  field :first_name, type: String, default: ""
  field :suffix, type: String, default: ""
  field :last_name, type: String, default: ""
  field :gender, type: String, default: ""
  field :date_of_birth, type: String, default: ""

  # for bulk selection
  field :bulk_selected_new_exercies, type: String
  
  # settings
  field :notes, type: String, default: ""
  field :authorisation_token, type: String, default: ""
  field :language, type: String, default: "nl"

  # api
  field :api_token,    type: String
  field :external_id,  type: String
  validates :external_id, uniqueness: { message: "The given external id is not unique in our system" } unless :is_client

  # introduction
  field :has_seen_intro, type: Boolean, default: false

  # gaming variables
  field :last_streak_update, type: DateTime, default: DateTime.now
  field :next_streak_update, type: DateTime, default: DateTime.now + 1.day
  field :streak_target, type: Integer, default: 7
  field :claimed_streaks, type: Integer, default: 0
  field :streak, type: Integer, default: 0
  field :streak_lock, type: Boolean, default: false #locks the streak untill reset

  def full_name
    unless name.blank?
      self.name
    else
      "#{self.first_name} #{self.suffix} #{self.last_name}"
    end
  end

  def is_client
    if self.roles.include? :client
      return true
    else
      return false
    end
  end

  def set_authorisation_token
    token = SecureRandom.urlsafe_base64(nil, false)
    self.authorisation_token = token
    self.save
    return token
  end

  def check_api_token
    if self.api_token.blank? & self.has_role?(:logopedist)
      token = SecureRandom.urlsafe_base64(nil, false)
      self.api_token = token
      self.save
    end
    return self.api_token
  end

  def active_exercises 
    active_ex = []
    self.exercises.each do |ex| 
      active_ex << ex unless ( ex.completed || ex.claimed_award )
    end
    active_ex
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  layout 'admin'
  include ApplicationHelper

  # https://github.com/bogdan/datagrid ?
  # https://github.com/bogdan/datagrid/wiki/Frontend

  # GET /users
  # GET /users.json
  def index

    if current_user.nil?
      redirect_to "/"
      return
    end

    unless current_user.has_role?(:admin )
      redirect_to "/admin/clients"
      return
    end
    # @page = ( params[:page]).to_i || 0
    # @resource = User.all
    # @total = @resource.count
    # @users = @resource.skip( @page * PER_PAGE ).limit( PER_PAGE)

    @page = ( params[:page]).to_i || 0
    if params[:search]
      @search = params[:search]
      @resource = User.or([{:name => /#{params[:search]}/i},{:email => /#{params[:search]}/i}] ).sort(:created_at => -1)
    else
      @search = ""
      @resource = User.all.sort(:created_at => -1)
    end
    @total = @resource.count
    @users = @resource.skip( @page * PER_PAGE ).limit( PER_PAGE )

  end


  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    # back
    @back = request.env["HTTP_REFERER"].split('https://app.voicebuddy.nl')[1]
    logger.debug "checking referrer"
    logger.debug @back

    # save ownership
    if current_user.has_role?(:logopedist)
      @user.logopedist = current_user
      @user.roles = [:client]
    end

    respond_to do |format|
      if @user.save
        format.html { redirect_to '/admin/users', notice: 'Alle wijzigingen zijn opgeslagen.' }
        format.json { render :show, status: :created, location: @user }
      else
        #format.html {
        #  logger.debug " --- "
        #  logger.debug "ERRORS: #{@user.errors.inspect}"
        #  logger.debug " --- "
        #  format.html { redirect_to '/admin/clients', notice: @user.errors.messages }
        #  redirect_to '/admin/clients'
        #}
        format.html {
          if current_user.has_role?(:logopedist)
            render 'admin/clients/new'
          else
            render :new
          end
        }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    #logger.debug " -------------------------- UPDATE : #{@user} #{user_params}"
    logger.debug " -------------------------- UPDATE : #{user_params[:bulk_selected_new_exercies]}"
    
    if user_params[:bulk_selected_new_exercies].blank?
      add_exercises = []
    else 
      add_exercises = JSON.parse( user_params[:bulk_selected_new_exercies] )      
    end 

    user_params.delete(:bulk_selected_new_exercies)
    
    logger.debug "parsed values:" + add_exercises.inspect 

    add_exercises.each do |ex|
      #add_new_exercise
      logger.debug "add: #{ex}"
      add_new_exercise( @user.id.to_s, ex["exercise_id"], ex["target"], ex["frequency"],  )
    end
    

    respond_to do |format|
      if @user.update(user_params)

        logger.debug "\n\n---\nGELUKT\n--\n\n"

        # format.html { redirect_to '/admin/users', notice: 'Alle wijzigingen zijn opgeslagen.' }
        format.html { render :edit, notice: 'Alle wijzigingen zijn opgeslagen.'  }
        format.json { render :show, status: :ok, location: @user }
      else
        logger.debug "\n\n---\ALLES IS KAPOT\n--\n\n"
        format.html { render :edit, notice: "er waren problemen. #{@user.errors.inspect}"  }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    back = request.env["HTTP_REFERER"].split('https://app.voicebuddy.nl')[1]
    if back.nil?
      back = request.env["HTTP_REFERER"].split('https://dev.voicebuddy.nl')[1]
    end

    respond_to do |format|
      format.html { redirect_to back, notice: "gebruiker #{@user.full_name} is verwijderd." }
      format.json { head :no_content }
    end
  end

  # IMPERSONATION --------------------------------------------------------------
  def impersonate
    user = User.find(params[:id])
    impersonate_user(user)
    redirect_to root_path
  end

  def stop_impersonating
    stop_impersonating_user
    redirect_to root_path
  end

  # internal use
  def add_new_exercise( _user_id, _ex_id, _target = nil, _frequency = nil)

    @user = User.find(_user_id)

    @user.exercises.each do |ex|
      logger.debug "trrr... #{ex.preset}, #{_ex_id}"
      if ex.preset.to_i == _ex_id.to_i && !ex.completed
        # skip
        logger.debug "oefening #{_ex_id} was al toegewezen aan de client"
        return
      end
    end

    preset = lookup_exercies( _ex_id )
    @exercise = Exercise.new()
    @exercise.user = @user
    @exercise.preset = _ex_id
    @exercise.name = preset["oefening"]

    if _target
      @exercise.target = _target.to_i
    else 
      @exercise.target = preset["target"]
    end

    if _frequency
      @exercise.frequency = _frequency.to_i
    else
      @exercise.frequency = preset["frequentie"]
    end

    @exercise.material = preset["materiaal"]
    @exercise.save()

    @user.exercises << @exercise
    @user.save

  end

  def add_exercise

    # {
    #  :id => 0,
    #  :name => "oefening 1",
    #  :video => "720p_5000kbps_h264_1.mp4",
    #  :beschrijving => "Lorem Ipsum solet dormit"
    #},

    # needs user to check doubloures
    @user = User.find(params[:id])

    # geen dubbele exercises
    # if user has exercis preset --> refuse
    @user.exercises.each do |ex|
      if ex.preset == params[:ex_id] && !ex.completed
        flash[:alert] = "User already has this preset."
        redirect_to "/admin/users/#{params[:id]}"
        return
      end
    end

    add_new_exercise( params[:id], params[:ex_id], params[:target], params[:freqency] )
    redirect_to "/admin/users/#{params[:id]}/edit#just_added"
  end

  def remove_exercise
    @exercise = Exercise.find(params[:ex_id])
    @exercise.destroy!
    redirect_to "/admin/users/#{params[:id]}/edit"
  end

  # not used
  def preview_video
    render :layout => false     
    @test = "123_rood_wit_blauw"
  end
  #

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      #params.fetch(:user, {:name, :email})
      params.require(:user).permit(:name, :email, :password, :language, :external_id, :logopedist, :bulk_selected_new_exercies, :roles => [])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.haml
.vakje
  = form_with( url: ( @user.persisted? ? "/admin/users/#{user.id}" : "/admin/users" ) , model: user, local: true) do |form|
    - if user.errors.any?
      #error_explanation
        %h2
          = t('activerecord.errors.template.header', :model => User.model_name.human, :count => @user.errors.count)

        %ul
          - user.errors.full_messages.each do |message|
            %li= message

    %label= t('common.name')
    = form.text_field :name
    %br

    %label= t('common.email')
    = form.text_field :email
    %br

    %label= t('common.language')
    = form.select :language, ["nl", "vls", "en", "fr"], {}, {:class=>""}
    %br

    - if current_user.has_role?(:admin)
      %label= t('common.roles')
      = form.select :roles, [["beheerder", :admin],["logopedist", :logopedist],["client", :client],["demo", :demo]], {}, {:multiple => true, :class=>"multiple_select"}
      %br

    - if current_user.has_role?(:logopedist)
      %label externe id
      = form.text_field :external_id
      %br

      %label api key (niet te wijzigen)
      %input.form-control.disabled{:disabled=>true, :type=>"text", :value=>@user.api_token}
      %br

    - elsif @user.has_role?(:logopedist)

      %label externe id
      = form.text_field :external_id
      %br

      %label api key (niet te wijzigen)
      %input.form-control.disabled{:disabled=>true, :type=>"text", :value=>@user.api_token}
      %br
      %br

      =# form.select :roles, [["client", :client]], {}, {:multiple => true, :class=>"multiple_select"}
    - else
      = form.hidden_field :roles, :multiple => true, :value=>"client"

    / add to current user -- don't do this!
    / = form.hidden_field :logopedist, :value => current_user.id.to_s

    - if !@user.persisted? #|| @user == current_user
      %p
        Let op: als u uw wachtwoord veranderd, wordt u gevraagd opnieuw in te loggen
      %label= t('common.password')
      = form.password_field :password
      %br

      %label= t('common.confirm_password')
      = form.password_field :password
      %br
      %br

    - if @user.persisted? && ( @user.has_role?(:client) || @user == current_user )
      %hr
      %h3#assigned_exercises
        = t('admin.clients.assigned_exercises')
        = "(#{user.exercises.where(:claimed_award => true).count}/"
        = "#{user.exercises.count})"
        %i.fa.fa-arrow-down

      %ul.huidige_oefeningen
        - @user.exercises.all.order(:created_at=>-1).sort_by{|k| k[:claimed_award].to_s }.each do |ex|
          = render partial: '/admin/oefening_item', :locals => {:exercise => ex}

      %hr

      %h3#available_exersises
        = t('admin.clients.available_exercises')
        = "(#{EXERCISES.count})"
        %i.fa.fa-arrow-down

      %ul.beschikbare_oefeningen

        .actions

          .filter-form{}
            %label= t('admin.clients.filter')
            %input#filter-input{:type=>"text"}        
          
          .filter-form{}
            %br
            &nbsp;
            %input#filter-existing{:type=>"checkbox"}
            %label{:style=>"display:inline"}= t('admin.clients.alles_tonen')

          .toepassen-form{:style=>"text-align:right;"}
            %br
            .pull-right= form.submit :value => t('common.save'), :class=>"emphasis"

        
        %hr
        - user_already_has_exercises = @user.active_exercises.map{|e| e.preset }
        = form.hidden_field :bulk_selected_new_exercies
        - EXERCISES.each do |ex|
          - if ex['id'].to_i.in?user_already_has_exercises
            - ex['hidden'] = "hidden was_assigned"
          - else 
            - ex['hidden'] = ""

          = render partial: '/admin/oefening_new', :locals => {:exercise => ex, :form => form}

    %hr

    %br
    .pull-right
      = form.submit :value => t('common.save'), :class=>"emphasis"
    %br
    %br

%br
%hr
%br

#text_modal
  .background
  .modal
    .modal-header
      .close_button.btn.btn-default x
      .title
    .modal-content
      .text
    .footer

/ depricated, we use a seperate viewer for this
#video_modal
  .background
  .modal
    .modal-header
      .close_button.btn.btn-default x
      .title
    .modal-content
      %video.videoplayer{:src=>"", :controls => true}
    .footer

- if @user.persisted? && ( @user.has_role?(:client) || @user == current_user )
  :javascript
    function init_exercises() {

      // dropdowns
      document.getElementById('assigned_exercises').onclick = function() {
        if ( document.querySelector('.huidige_oefeningen').style.display != "none" ) {
          document.querySelector('.huidige_oefeningen').style.display = "none"
        }else{
        document.querySelector('.huidige_oefeningen').style.display = "block"
        }
      }
      //document.querySelector('.huidige_oefeningen').style.display = "none"

      document.getElementById('available_exersises').onclick = function() {
        if ( document.querySelector('.beschikbare_oefeningen').style.display != "none" ) {
          document.querySelector('.beschikbare_oefeningen').style.display = "none"
        }else{
        document.querySelector('.beschikbare_oefeningen').style.display = "block"
        }
      }
      document.querySelector('.beschikbare_oefeningen').style.display = "none"

      // filters
      document.getElementById('filter-input').oninput = function(evt) {
        document.querySelectorAll('.new_exercise').forEach( function(_elm) {
          _elm.style.display = "block"
          currentInput = evt.target.value.toLowerCase()
          if (currentInput.length > 3) {
            _elm.style.display = "none"

            console.log( _elm.querySelector('.title').innerText )

            if ( _elm.querySelector('.title').innerText.toLowerCase().indexOf(currentInput) != -1 ) {
              _elm.style.display = "block"
            }

            if ( _elm.querySelector('.category').innerText.toLowerCase().indexOf(currentInput) != -1 ) {
              _elm.style.display = "block"
            }

            if ( _elm.querySelector('.tags').innerText.toLowerCase().indexOf(currentInput) != -1 ) {
              _elm.style.display = "block"
            }
          }
        })
      }
    }

    function show_text( _title, _text ) {
      var modal = document.getElementById('text_modal')
      modal.querySelector(".title").innerHTML = _title
      modal.querySelector(".text").innerHTML = _text
      modal.querySelector(".close_button").onclick = function() {
        modal.style.display = "none"
      }
      modal.style.display = "block"
    }

    function open_video_modal(_url) {

      var modal = document.getElementById('video_modal')
      modal.querySelector(".videoplayer").src = _url
      //modal.querySelector(".text").innerHTML = _text
      modal.querySelector(".close_button").onclick = function() {
        modal.style.display = "none"
        modal.querySelector(".videoplayer").pause()
      }
      modal.style.display = "block"
    }
    
    document.getElementById('filter-existing').onchange = function( checkbox ) {         
      document.querySelectorAll('.was_assigned').forEach( function( oefening ) {
        if ( checkbox.target.checked ) {
          oefening.classList.remove('hidden')
        }else{
          oefening.classList.add('hidden')
        }
      })
    }

    var bulk_selected_new_exercies = []
    document.querySelectorAll('.select_new_exercise').forEach( function(checkbox) {
      console.log("oi", checkbox.checked )
      console.log("oi", checkbox )

      checkbox.onchange = function( checkbox ) {
        console.log("oi oi", checkbox.target.checked )
        console.log(checkbox.target)
        var _id = checkbox.target.dataset.id
        if (checkbox.target.checked) {        
          document.getElementById("new_exercise_"+_id).classList.add('selected')        
        }else{
          document.getElementById("new_exercise_"+_id).classList.remove('selected')
        }

        update_new_exercises()
      }
    })

    function update_new_exercises() {
      bulk_selected_new_exercies = []
      document.querySelectorAll('.new_exercise.selected').forEach(function(elm) {
        console.log("got id for selected", elm.dataset.id )
        ex = {
          "exercise_id": elm.dataset.id, 
          "frequency": document.getElementById('frequency_' + elm.dataset.id).value,
          "target": document.getElementById('target_' + elm.dataset.id).value
        }

        bulk_selected_new_exercies.push(ex)
      })

      // updated array
      console.log(bulk_selected_new_exercies)
      
      // update hidden
      document.getElementById("user_bulk_selected_new_exercies").value = JSON.stringify(bulk_selected_new_exercies)
      // document.getElementById("user_bulk_selected_new_exercies").value = bulk_selected_new_exercies.join(",")
    }

    document.querySelectorAll('.new_exercise_input').forEach( function(input_element) {
      input_element.onchange = function() { update_new_exercises() }
      input_element.ontext = function() { update_new_exercises() }
      input_element.oninput = function() { update_new_exercises() }
    })

    // main
    init_exercises();

app/views/admin/users/_old_form.html.erb
<div class="vakje">
<%= form_with(url: "/admin/users/#{user.id}", model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <label> name </label>
  <%= form.text_field :name %>
  <br>

  <label> email </label>
  <%= form.text_field :email  %>
  <br>

  <label> roles </label>
  <%= form.select :roles, [["beheerder", :admin],["logopedist", :logopedist],["client", :client],["demo", :demo]], {}, {:multiple => true, :class=>"multiple_select"} %>
  <br>

  <!--
  <label> password </label>
  <%#= form.password_field :password  %>
  -->
  

  <br>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>
</div>

<br>
<hr>
<br>

app/views/admin/users/edit.html.haml
%h1
  = @user.full_name
  %small
    %br
    %small= @user.email

= render 'form', user: @user
= link_to t('common.show'), "/admin/users/#{@user.id.to_s}"
|
\#{link_to t('common.back'), admin_users_path}

app/views/admin/users/index.html.haml
%h1= t('admin.users.title')

.filters
  .pull-right{:style=>"float:right;"}
    %input#search_input{:value=>@search}
    %button#search search

  %p
    Page:
    %b= @page * PER_PAGE
    \/
    %b= @total

.vakje
  %table
    %thead
      %tr
        %th= t('common.name')
        %th= t('comomn.email')
        %th= t('common.language')
        %th= t('common.roles')
        %th= t('common.exercises')
        %th logopedist
        %th{:colspan=>"4"}
    %tbody>
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.email
          %td= user.language
          %td= user.roles.to_sentence
          %td= user.exercises.count
          %td= user.logopedist.email unless user.logopedist.nil?
          //%td= link_to t('common.show'), "/admin/users/#{user.id.to_s}"
          %td{:style=>"text-align:center"}= l(user.created_at, :format => :short)
          %td= link_to t('common.impersonate'), "/admin/impersonate/#{user.id.to_s}"
          %td= link_to t('common.edit'), edit_admin_user_path(user)
          %td= link_to t('common.destroy'), "/admin/users/#{user.id.to_s}", method: :delete, data: { confirm: 'Are you sure?' }

  %br
    = render "/admin/partials/pagination", :pagination_for => "users"

  %br

%br
%hr
%br
= link_to ' + Maak nieuwe gebruiker', new_admin_user_path, :class => "btn btn-turq"


:javascript
  document.getElementById('search').onclick = function() {
    window.location.search = "?page=0&search=" + document.getElementById('search_input').value
  }

  var next_page = function( _page ) {
    window.location.href = "/admin/users/?page=" + _page + "&search=" + document.getElementById('search_input').value
  }

  var prev_page = function( _page ) {
    window.location.href = "/admin/users/?page=" + _page + "&search=" + document.getElementById('search_input').value
  }

  window.onkeyup = function(evt) {
    console.log(evt.which)
    if (evt.which  == "13" ) {
      window.location.search = "?page=0&search=" + document.getElementById('search_input').value
    }
  }

app/views/admin/users/my_profile.html.haml
%h1 Mijn profiel

app/views/admin/users/new.html.haml
%h1= t('common.new')
= render 'form', user: @user
= link_to 'Back', admin_users_path

app/views/admin/users/old_index.html.erb
= unless notice.blank?
  %p#id.notice= notice

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.roles.to_sentence %></td>
        <td><%= link_to 'Show', "/admin/users/#{user.id.to_s}" %></td>
        <td><%= link_to 'Impersonate', "/admin/impersonate/#{user.id.to_s}" %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', "/admin/users/#{user.id.to_s}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/preview_video.html.haml
%center
 %video.videoplayer#videoplayer{:src=> params[:url], :controls => true, :autoplay => true}

:javascript
  document.getElementById('videoplayer').play()

:css
  body, html, video {
    margin: 0;
    with: 100vw;
    height: 100vh;
    background-color: black;
  }
  video {
    margin: auto;
  }

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<pre>
  <%= @user.to_yaml %>
</pre>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>