config/routes.rb
Rails.application.routes.draw do

  resources :exercises
  delete 'remove_exercise/:id' => 'exercises#remove_exercise'
  devise_for :users, controllers: {sessions: "sessions"}


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # scope admin
  get '/admin/dashboard', to: 'admin#dashboard'
  get '/admin/index', to: 'admin#index'
  get '/admin/my_profile', to: 'admin#my_profile'

  # admin, superadmin only
  get '/admin/logopedisten', to: 'admin#logopedisten'
  get '/admin/logs', to: 'admin#logs'

  # api functions
  get '/api/sso', to: 'api#sso'
  post '/api/add_client', to: 'api#add_client_for_user'
  get '/api/client_credentials', to: 'api#get_client_credentials'

  authenticated do
    get 'site/demo', to: 'site#demo'
  end

  # users
  namespace :admin do
    resources :users
    get 'users/:id/add_exercise/:ex_id', to: 'users#add_exercise'
    get 'users/:id/remove_exercise/:ex_id', to: 'users#remove_exercise'
    get 'preview_video/', to: 'users#preview_video'
    get 'clients', to: 'clients#index'
    get 'clients/new', to: 'clients#new'
    get 'clients/:id', to: 'clients#show'
    get 'reset_password_email/:id', to: 'clients#reset_password_email'
    get 'impersonate/(:id)' => 'users#impersonate', as: :impersonate
    #get 'stop_impersonating' => 'users#stop_impersonating', as: :stop_impersonate
    post 'stop_impersonating' => 'users#stop_impersonating', as: :stop_impersonate
  end

  # for everyone
  get '/users/my_profile', to: 'users#my_profile'

  # scope?
  # get '/app/test_api', to: 'app#test_api'
  get '/app/login(/:login)', to: 'app#login'
  post '/app/new_login', to: 'app#new_login'
  get '/app/login_failed', to: 'app#login_failed'
  get '/app/forgot_password', to: 'app#forgot_password'

  get '/app/introductie(/:token)', to: 'app#introductie'
  get '/app/info(/:token)', to: 'app#info'
  get '/app/awards(/:token)', to: 'app#awards'
  get '/app/awards/claim/:id(/:token)', to: 'app#claim_reward'
  get '/app/claim_reward/:id(/:token)', to: 'app#claim_reward'
  get '/app/claim_streak/(:token)', to: 'app#claim_streak'
  get '/app/oefening/:id(/:token)', to: 'app#oefening'
  get '/app/oefeningen(/:token)', to: 'app#oefeningen'
  get '/app/my_profile(/:token)', to: 'app#my_profile'
  get '/app/update_exercise/:id/:token', to: 'exercises#update_exercise'
  get '/app(/:token)', to: 'app#index'

  # forgot pass? -- for app users
  get '/app/password/sent' => 'app#forgot_password_confirm'
  get '/app/password/new' => 'app#forgot_password'
  get '/app/password/edit(/:user_id)' => 'app#edit_password', as: :app_password_edit
  patch '/app/password' => 'app#update_password'
  put '/app/password' => 'app#update_password'
  post '/app/password' => 'app#create_password'

  # scope site
  get '/site/index', to: 'site#index'
  get '/site/test', to: 'site#test'
  get '/site/app', to: 'site#app'

  # aliasses
  get '/sign_up', to: redirect('/users/sign_up')
  get '/inschrijven', to: redirect('/users/sign_in')
  get '/inloggen', to: redirect('/users/sign_in')
  get '/login', to: redirect('/users/sign_in')

  # test
  get 'autologintest', to: 'app#autologintest'

  root to: 'application#index'
  # match '*all', controller: 'application', action: 'cors_preflight_check', via: [:options]

  # config/routes.rb
  resources :web_hits, :only=>[:create]
  match '*all', :controller => 'web_hits', :action => 'options', :constraints => {:method => 'OPTIONS'}, via: [:options]

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]
  layout 'admin'

  # GET /exercises
  # GET /exercises.json
  def index
    # TODO: move to modal
    @limit = params[:limit].blank? ? 50 : params[:limit].to_i
    @page = params[:page].blank? ? 0 : (params[:page].to_i - 1) 

    if current_user.has_role?(:admin)
      @total = Exercise.all().count
      @exercises = Exercise.all().limit(@limit).skip(@page*@limit)      
    else
      @clients = User.where(:logopedist => current_user, :roles.in => [:client]).map{|u| u.id.to_s }
      @total = Exercise.where(:user_id.in => @clients ).count
      @exercises = Exercise.where(:user_id.in => @clients ).limit(@limit).skip(@page*@limit)
    end
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # DELETE /admin/remove_exercise/1
  def remove_exercise
    if params[:id].nil?
      render plain: "Error no exercide id found"
    end

    @exercise = Exercise.find(params[:id])
    if @exercise.nil?
      render plain: "Error no exercise found for id #{params[:id]}"
    end

    user_id = @exercise.user.id.to_s

    if @exercise.destroy
      flash.alert = "Exercise was destroyed."
      flash.notice = "Exercise was destroyed."
    else
      flash.alert = "alles is kapot."
      flash.notice = "alles is kapot."
    end

    redirect_to "/admin/users/#{user_id}/edit"
    #render plain: "We've gathered here to remove exercise #{params[:id]}"
  end

  # ----------------------------------------------------------------------------
  # Fot tha app
  def update_exercise
    user = User.where(:authorisation_token => params[:token]).first()
    exercise = Exercise.find( params[:id] )

    if user.blank?
      logger.debug "# # # # # # # #"
      logger.debug "# USER COULD NOT BE VERIFIED"
      logger.debug "# # # # # # # #"
      render html:" # # # # # # # #  User could not be verified"
    end

    if exercise.user_id == user.id
      if exercise.update_progress
        render html: "Oefening afgerond!"
      else
        render html: "Oefning kon niet worden opgeslagen!"
      end
    else
      render plain: "Gebruiker en oefening komen niet overeen"
    end
  end

  # ----------------------------------------------------------------------------
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exercise_params
      params.require(:exercise).permit(:name, :afgerond, :video, :description, :preset, :claimed_award, :completed, :target, :achieved, :frequency, :completed_for_the_day)
    end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.haml
- preset = lookup_exercies(@exercise.preset)
= form_with(model: exercise, local: true) do |form|
  - if exercise.errors.any?
    #error_explanation
      %h2
        = pluralize(exercise.errors.count, "error")
        prohibited this exercise from being saved:
      %ul
        - exercise.errors.full_messages.each do |message|
          %li= message
  /.field
  /  = form.label :name
  /  = form.text_field :name

  /%pre= EXERCISES
  %br
  %br
  %hr
  %br
  .field
    = form.label :preset
    = form.select :preset, EXERCISES.map{|e| e['id'] }, {class:'test', :disabled=>true}

  .field
    = form.label :naam
    %p= preset[I18n.locale.to_s]["naam"]

  .field
    = form.label :doel
    %p= preset[I18n.locale.to_s]["doel"]

  .field
    = form.label :inhoud
    %p= preset[I18n.locale.to_s]["content"]


  %hr/
  .field
    = form.label :completed_for_the_day
    = form.select :completed_for_the_day, [true, false], {class:'test', :disabled=>true}

  .field
    = form.label :completed
    = form.select :completed, [true, false], {class:'test'}

  .field
    = form.label :claimed_award
    = form.select :claimed_award, [true, false], {class:'test'}
  %hr/
  .field
    = form.label "doel (aantal dagen)"
    = form.number_field :target

  .field
    = form.label "frequentie (aantal keer per dag)"
    = form.number_field :frequency


  .field
    %p#exercise_info ...

  %hr
  .field
    = form.label "tot nu toe gehaald, totaal"
    //  = form.text_field :achieved
    %pre= @exercise.achieved_array

  .field
    = form.label "tot nu toe gehaald, vandaag"
    //  = form.text_field :achieved
    %pre= @exercise.achieved_array_today

  /.field
  /  = form.label :streak
  /  = form.text_field :streak
  /.field
  /  = form.label :streak_expire
  /  = form.datetime_field :streak_expire
  /.field
  /  = form.label :frequency
  /  = form.text_field :frequency
  /.field
  /  = form.label :streak
  /  = form.text_field :streak
  /.field
  /  = form.label :streak_expire
  /  = form.text_field :streak_expire
  /.field
  /  = form.label :streak_target
  /  = form.text_field :streak_target
  /.field
  /  = form.label :achieved_in_streak
  /  = form.text_field :achieved_in_streak
  /.field
  /  = form.label :complete_streak
  /  = form.text_field :complete_streak


  /.field
  /  = form.label :afgerond
  /  = form.text_field :afgerond

  /.field
  /  = form.label :preset
  /  = form.select :preset, EXERCISES.map{|e| [e["naam"],e["id"]] }, {}, {class:'test'}
  /.field
  /  = form.label :description
  /  = form.text_field :description
  %hr
  .actions
    = form.submit :value => t('common.save')

:javascript
  function update_total() {
    target = document.getElementById('exercise_target').value
    freq = document.getElementById('exercise_frequency').value
    total = target * freq
    document.getElementById('exercise_info').innerHTML = `<strong>${freq}</strong> oefeningen per dag, <strong>${target}</strong> dagen lang, dat zijn in totaal <large><strong>${total}</strong></large> oefeningen.`
  }

  document.getElementById('exercise_target').onchange = document.getElementById('exercise_frequency').onchange = update_total
  update_total()

app/views/exercises/edit.html.haml
.vakje
  %h1 Wijzig oefening
  oefning hoor bij
  = link_to edit_admin_user_path(@exercise.user) do
    = @exercise.user.full_name
    = @exercise.user.email
  %br

  #{render 'form', exercise: @exercise}

%hr
= link_to 'Bewerk', edit_exercise_path(@exercise)
|
= link_to 'Terug naar alle oefeningen', exercises_path
|
= link_to 'Terug naar de Client', edit_admin_user_path(@exercise.user)

app/views/exercises/index.html.haml

%h1= t('common.exercises')

.pagination
  .page_selection.pull-right
    %select#change_page{:style=>"width: 120px;"}
      - pages = (@total/@limit).ceil()
      - index = 0
      - while index < pages do
        - index = index + 1 
        - if @page + 1 == index 
          %option{:value=>index, :selected=>"selected"}
            Page 
            = index
        - else
          %option{:value=>index}                
            Page 
            = index

  .info
    totaal: 
    = @total
    &nbsp; | &nbsp;
    pagina: 
    = @page + 1

%br
%hr 

.vlakje
  %table
    %thead
      %tr
        %th Id
        %th naam
        %th toegewezen aan?
        %th afgerond?
        %th content
        %th doel
        %th preset
        %th{:colspan=>"3"}

    %tbody
      - @exercises.each do |exercise|
        %tr
          %td= exercise.preset
          %td= lookup_exercies(exercise.preset)["nl"]["naam"]
          %td= exercise.user.full_name unless exercise.user.nil?
          %td= exercise.completed
          %td= lookup_exercies(exercise.preset)["nl"]["content"]
          %td
            = lookup_exercies(exercise.preset)["nl"]["doel"][0..40].gsub(/\s\w+$/,'')
            \...

          %td= exercise.preset
          %td
            = link_to exercise do
              %i.fas.fa-eye

          %td
            =link_to edit_exercise_path(exercise)  do
              %i.fas.fa-edit

          %td
            = link_to exercise, method: :delete, data: { confirm: 'Are you sure?' } do
              %i.fas.fa-trash-alt


  %br

  =# link_to t('exercies.new'), new_exercise_path
  :javascript 
    document.getElementById('change_page').onchange = function() { 
      window.location.search = "&page=" + document.getElementById('change_page').value
    }    

app/views/exercises/new.html.erb
<h1>New Exercise</h1>

<%= render 'form', exercise: @exercise %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/old_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exercises</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Afgerond</th>
      <th>Video</th>
      <th>Description</th>
      <th>Preset</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.each do |exercise| %>
      <tr>
        <td><%= exercise.name %></td>
        <td><%= exercise.afgerond %></td>
        <td><%= exercise.video %></td>
        <td><%= exercise.description %></td>
        <td><%= exercise.preset %></td>
        <td><%= link_to 'Show', exercise %></td>
        <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
        <td><%= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exercise', new_exercise_path %>

app/views/exercises/show.html.haml
%p#notice= notice
- preset = lookup_exercies(@exercise.preset)

%p
  %strong Oefening Name:
  = preset[I18n.locale.to_s]["naam"]

%p
  %strong Toegewezen aan:
  = @exercise.user.full_name unless @exercise.user.nil?

%p
  %strong
    Afgerond:
  = @exercise.completed

%p
  %strong
    Status:
  %pre
    = @exercise.achieved_array
    (totaal)

    = @exercise.achieved_array_today
    (vandaag)
  .score
    = (@exercise.score * 0.1).round(1)
    \%

%p
  %strong
    materiaal type:
  = @exercise.material

%p
  %strong inhoud:
  %br
  %pre= preset[I18n.locale.to_s]["content"]

%p
  %strong beschrijving:
  %br
  = preset[I18n.locale.to_s]["doel"]

%br
%br
%hr
= link_to 'Bewerk', edit_exercise_path(@exercise)
|
= link_to 'Terug naar alle oefeningen', exercises_path
|
= link_to 'Terug naar de Client', edit_admin_user_path(@exercise.user)