config/routes.rb
Rails.application.routes.draw do

  resources :exercises
  delete 'remove_exercise/:id' => 'exercises#remove_exercise'
  devise_for :users, controllers: {sessions: "sessions"}


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # scope admin
  get '/admin/dashboard', to: 'admin#dashboard'
  get '/admin/index', to: 'admin#index'
  get '/admin/my_profile', to: 'admin#my_profile'

  # admin, superadmin only
  get '/admin/logopedisten', to: 'admin#logopedisten'
  get '/admin/logs', to: 'admin#logs'

  # api functions
  get '/api/sso', to: 'api#sso'
  post '/api/add_client', to: 'api#add_client_for_user'
  get '/api/client_credentials', to: 'api#get_client_credentials'

  authenticated do
    get 'site/demo', to: 'site#demo'
  end

  # users
  namespace :admin do
    resources :users
    get 'users/:id/add_exercise/:ex_id', to: 'users#add_exercise'
    get 'users/:id/remove_exercise/:ex_id', to: 'users#remove_exercise'
    get 'preview_video/', to: 'users#preview_video'
    get 'clients', to: 'clients#index'
    get 'clients/new', to: 'clients#new'
    get 'clients/:id', to: 'clients#show'
    get 'reset_password_email/:id', to: 'clients#reset_password_email'
    get 'impersonate/(:id)' => 'users#impersonate', as: :impersonate
    #get 'stop_impersonating' => 'users#stop_impersonating', as: :stop_impersonate
    post 'stop_impersonating' => 'users#stop_impersonating', as: :stop_impersonate
  end

  # for everyone
  get '/users/my_profile', to: 'users#my_profile'

  # scope?
  # get '/app/test_api', to: 'app#test_api'
  get '/app/login(/:login)', to: 'app#login'
  post '/app/new_login', to: 'app#new_login'
  get '/app/login_failed', to: 'app#login_failed'
  get '/app/forgot_password', to: 'app#forgot_password'

  get '/app/introductie(/:token)', to: 'app#introductie'
  get '/app/info(/:token)', to: 'app#info'
  get '/app/awards(/:token)', to: 'app#awards'
  get '/app/awards/claim/:id(/:token)', to: 'app#claim_reward'
  get '/app/claim_reward/:id(/:token)', to: 'app#claim_reward'
  get '/app/claim_streak/(:token)', to: 'app#claim_streak'
  get '/app/oefening/:id(/:token)', to: 'app#oefening'
  get '/app/oefeningen(/:token)', to: 'app#oefeningen'
  get '/app/my_profile(/:token)', to: 'app#my_profile'
  get '/app/update_exercise/:id/:token', to: 'exercises#update_exercise'
  get '/app(/:token)', to: 'app#index'

  # forgot pass? -- for app users
  get '/app/password/sent' => 'app#forgot_password_confirm'
  get '/app/password/new' => 'app#forgot_password'
  get '/app/password/edit(/:user_id)' => 'app#edit_password', as: :app_password_edit
  patch '/app/password' => 'app#update_password'
  put '/app/password' => 'app#update_password'
  post '/app/password' => 'app#create_password'

  # scope site
  get '/site/index', to: 'site#index'
  get '/site/test', to: 'site#test'
  get '/site/app', to: 'site#app'

  # aliasses
  get '/sign_up', to: redirect('/users/sign_up')
  get '/inschrijven', to: redirect('/users/sign_in')
  get '/inloggen', to: redirect('/users/sign_in')
  get '/login', to: redirect('/users/sign_in')

  # test
  get 'autologintest', to: 'app#autologintest'

  root to: 'application#index'
  # match '*all', controller: 'application', action: 'cors_preflight_check', via: [:options]

  # config/routes.rb
  resources :web_hits, :only=>[:create]
  match '*all', :controller => 'web_hits', :action => 'options', :constraints => {:method => 'OPTIONS'}, via: [:options]

end

app/views/layouts/admin.html.haml
!!! 5
%html{lang: I18n.locale}
  %head
    %title
      VoiceBuddy
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', :media => 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'admin', 'data-turbolinks-track': 'reload'
    = favicon_link_tag asset_path('favicon')
    %link{:rel=>"apple-touch-icon", :sizes=>"128x128", :href=>"/logo_128_touch_icon.png"}

    / Google analytics
    = javascript_include_tag 'https://www.googletagmanager.com/gtag/js?id=G-TZQGK0HWC1'
    :javascript
      <!-- Global site tag (gtag.js) - Google Analytics -->
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-TZQGK0HWC1');

  %body#admin

    .grid-container
      %header.header
        = render partial: '/admin/header'

      - if current_user != true_user
        You (#{true_user.name}) are signed in as #{current_user.name}#{link_to "Back to admin", admin_stop_impersonate_path, method: :post}


      .menu
        = render partial: '/admin/menu'

      .main-content
        - unless notice.blank?
          %p#id.notice= notice

        = yield

app/views/layouts/app.html.haml
!!! 5
%html{lang: I18n.locale}
  %head
    %title
      - unless @exercise.blank?
        = lookup_exercies(@exercise.preset)[current_user.language]["naam"]
      - else
        = @title

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', :media => 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'app/app', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag asset_path('favicon')

    / Google analytics
    = javascript_include_tag 'https://www.googletagmanager.com/gtag/js?id=G-TZQGK0HWC1'
    :javascript
      <!-- Global site tag (gtag.js) - Google Analytics -->
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-TZQGK0HWC1');

    %link{:rel=>"apple-touch-icon", :sizes=>"128x128", :href=>"logo_128_touch_icon.png"}
    %meta{:name=>"format-detection", :content=>"telephone=yes"}
    %meta{:name=>"viewport", :content=>"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"}
    %meta{:name=>"msapplication-tap-highlight", :content=>"no"}
    %meta{:name=>"color-scheme", :content=>"light"}
    %meta{:name=>"turbolinks-visit-control", :content=>"reload"}

  %body#app{'data-token' => @token}

    //%pre DEV!
    .app-container

      - if current_user != true_user
        You (#{true_user.name}) are signed in as #{current_user.name}#{link_to "Back to admin", admin_stop_impersonate_path, method: :post}


      .main-content
        = yield

      .menu
        = render partial: '/app/bottom_menu'

app/views/layouts/application.html.haml
!!! 5
%html{lang: I18n.locale}
  %head
    %title
      VoiceBuddy
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', :media => 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag asset_path('favicon')
    %link{:rel=>"apple-touch-icon", :sizes=>"128x128", :href=>"logo_128_touch_icon.png"}

    / Google analytics
    = javascript_include_tag 'https://www.googletagmanager.com/gtag/js?id=G-TZQGK0HWC1'
    :javascript
      <!-- Global site tag (gtag.js) - Google Analytics -->
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-TZQGK0HWC1');

  %body#site

    .grid-container
      %header.header
        = render partial: '/site/header'

      .main-content
        /- flash.each do |type, msg|
        /  .alert.alert-info= msg
        - unless notice.blank?
          %p#id.notice= notice

        = yield

      %footer.footer